### ISSUE TITLE
compiling stucks on ant build

### ISSUE THREAD

**Issue by max037** [Drahflow/DrahflowsAR#2]
hey,

i tried to compile it via linux. I guess, i took the right ndk, but the compiling stucks by the ant build. In my opinion, it is evoked by the missing "build.xml" file.

could you please provide me a solution how to manage to compile the apk.

thank you very much

**Comment by Drahflow** [comment]
Indeed. I never noticed, because locally the file existed (naturally). :(

I now added it: https://github.com/Drahflow/DrahflowsAR/commit/a99e2e5a41a0e1c5b5d17e7e11d88d685865efa3
Thank you very much for bringing it to my attention.
